### ISSUE TITLE
How to make this DO something??

### ISSUE THREAD

**Issue by obcocav** [pablogventura/OctoPrint-PowerFailure#15]
So I have the plug installed.  Configuration panel shows up fine.  Tried the auto restart both on and off.  Still don’t see any gcode file generated and nothing happens when the power comes back on…

what am I missing?

thanks

**Comment by paukstelis** [comment]
Make sure you have error handling set to Disconnect, not Cancel. 
![image](https://user-images.githubusercontent.com/28326982/216429299-4d97295d-0e6d-4d71-a8d2-61d650dd71dd.png)

**Comment by paukstelis** [comment]
You could also provide output from octoprint.log file after restarting from a disconnect.
