### ISSUE TITLE
Bugs in wizard

### ISSUE THREAD

**Issue by thomergil** [pablogventura/OctoPrint-PowerFailure#27]
Thanks for working on this.

One, there is no Next button, which the text refers to. There is only a Finish button, which takes the user to a broken github page. This means OctoPrint is now stuck on the Wizard page with no way to access the main interface. You essentially bricked OctoPrint. 😞

**Comment by thomergil** [comment]
It looks like the <a> surrounds the buttons, making it impossible to click on the Finish button without going to the broken link.

**Comment by thomergil** [comment]
You should fix this immediately.

**Comment by thomergil** [comment]
...even when the missing " is fixed, the Finish button doesn't do anything.

**Comment by paukstelis** [comment]
It has already been fixed. Reinstall the plugin.

**Comment by thomergil** [comment]
I can't. Because the wizard blocks access to anything else.

**Comment by paukstelis** [comment]
append `recovery` to your url, e.g.  http://octopi.local/recovery
Remove the plugin and reinstall.

**Comment by thomergil** [comment]
Thank you.

**Comment by RicSkye** [comment]
How do I remove the plugin in safe mode?

**Comment by dioimnc** [comment]
When I'm in the recovery menu it won't switch to safe mode, saying "You lack admin permissions."
Im the only user so I should be admin right? What to do?

**Comment by paukstelis** [comment]
You can also just delete the plugin.
Assuming you are using OctoPi, ssh into the Pi:
`rm -rf ~/oprint/lib/python3.7/site-packages/octoprint_powerfailure`
Depending on your OctoPi version that `python3.7` might be something else, in which case you would need to change accordingly.

**Comment by dioimnc** [comment]
Okay, that worked out well. Thanks for the quick support, I appreciate it.

**Comment by paukstelis** [comment]
> Okay, that worked out well. Thanks for the quick support, I appreciate it.

You can reinstall the plugin and it will be fixed from now on.

**Comment by dioimnc** [comment]
> 

I did and everything worked fine this time. Thanks again.
