### ISSUE TITLE
After updated to the last version as of today (2023.06.07), OctoPi web grayed out

### ISSUE THREAD

**Issue by jjvelar** [pablogventura/OctoPrint-PowerFailure#28]
After updated to the last version as of today (2023.06.07), OctoPi web grayed out.
Please advise.

**Comment by paukstelis** [comment]
There seems to be an issue with it displaying the new Wizard on an update. Refresh the web browser (ctrl+reload, or ctrl+shift+reload).

**Comment by jjvelar** [comment]
> There seems to be an issue with it displaying the new Wizard on an update. Refresh the web browser (ctrl+reload, or ctrl+shift+reload).

This didn't work for me.
